### ISSUE TITLE
got script error opening the addon

### ISSUE THREAD

**Issue by peppesr** [karrukola/plugin.audio.deejayIt.reloaded#11]
i have a script error launching the addon, in the log i see something related to 404 problem.

**Comment by karrukola** [comment]
Odd: the plugin should be able to manage website error conditions and
report them to the user.
Its main limitation is that it is using lxml which is not part of the
default python package.
Would you please attache the logs?
Mind I ask where are you from? I thought I would have had only Italians
speaking users.

Filippo

**Comment by peppesr** [comment]
Ciao Filippo,
sono italiano, di Siracusa. qui allegato il log.
http://pastebin.com/raw.php?i=jpaU8bud
effettivamente guardando con attenzione il log (10:09:16 T:4464) l'errore è legato come tu mi anticipi all' lxml. 
l'errore 404 di cui ti parlavo non lo trovo più. magari è stata una mia svista.
è un'installazione di prova con solo il tuo addon installato.
Peppe

**Comment by karrukola** [comment]
Ciao,
per installare lxml puoi dare pip install lxml dalla console python, se
stai usando un pc è il modo più veloce.

Per risolvere meglio questo problema devo cambiare la libreria che legge il
sito web, ma non son sicuro di poterlo fare in poco tempo.

Se non riesci puoi usare questa vecchia versione, che non usa lxml, ma
putroppo non mostra tutti i contenuti.
https://github.com/karrukola/plugin.audio.deejayIt.reloaded/archive/1.0.2.zip

Filippo

Il giorno 28 gennaio 2015 10:13, peppesr <notifications@github.com> ha
scritto:

**Comment by peppesr** [comment]
Grazie Filippo.
uso windows quindi probabilmente non avrò problemi.
grazie per il supporto.
Peppe

**Comment by karrukola** [comment]
This issue is fixed in version 1.4.x. Request to include 1.4.0 in Kodi's addon library has been submitted.
